import type { HeroDefinition } from "./HeroDefinition";

export const MARINE = Object.freeze({
  id: "marine",
  displayName: "Marine",
  movementSpeedMetresPerSecond: 5.25,
  collisionRadiusMetres: 0.55,
  evasiveMove: {
    presentation: "roll",
    durationSeconds: 0.55,
    distanceMetres: 4,
    invulnerabilitySeconds: 0.25,
  },
  defence: {
    armour: 0,
    flatDamageReduction: 0,
    maxShield: 0,
    shieldRechargeDelaySeconds: 3,
    shieldRechargePerSecond: 0.8,
    slowResistance: 0,
    attackSpeedMultiplier: 1,
    hitInvulnerabilitySeconds: 0.65,
    mineralFindPercent: 100,
  },
  weaponProficiencies: {
    light: 0,
    medium: 0,
    heavy: 0,
    unique: 0,
  },
  levelGrowth: {
    health: 1,
    armour: 1,
    damage: 1,
    speed: 1,
    supportEffect: 0,
    proficiency: { light: 1 },
  },
  passive: {
    id: "entrenched",
    name: "Entrenched",
    description: "Holding your ground for 1 second grants +3 armour until you move.",
    stationarySecondsRequired: 1,
    bonusArmour: 3,
  },
  upgradeSlots: {
    offensive: 3,
    defensive: 2,
    support: 1,
    scavenger: 1,
  },
  ultimate: {
    id: "bastion-barrage",
    name: "Bastion Barrage",
    description: "Launch an explosive volley in every direction.",
    cooldownSeconds: 24,
    projectileCount: 12,
    projectileDamage: 4,
    explosionRadiusMetres: 1.4,
  },
} satisfies HeroDefinition);
