import type { HeroDefinition } from "./HeroDefinition";
import { scoutUnlockRequirementText } from "../progression/ArmoryProgression";

/** T4.10 mechanics candidate; art, audio, clearance, and deployment remain gated. */
export const SCOUT = Object.freeze({
  id: "scout",
  displayName: "Scout",
  role: "High-mobility reconnaissance and precision fire",
  baseMaxHealth: 8,
  baseRegenerationPerSecond: 0,
  movementSpeedMetresPerSecond: 6,
  collisionRadiusMetres: 0.48,
  evasiveMove: {
    presentation: "dash",
    durationSeconds: 0.34,
    distanceMetres: 5,
    invulnerabilitySeconds: 0.22,
  },
  defence: {
    armour: 0,
    flatDamageReduction: 0,
    maxShield: 0,
    shieldRechargeDelaySeconds: 3,
    shieldRechargePerSecond: 0.8,
    slowResistance: 0.2,
    attackSpeedMultiplier: 1,
    hitInvulnerabilitySeconds: 0.6,
  },
  weaponProficiencies: { light: 0, medium: 0, heavy: 0, unique: 0 },
  levelGrowth: {
    health: 0,
    armour: 0,
    damage: 1,
    speed: 2,
    supportEffect: 0,
    proficiency: { light: 1 },
  },
  passive: {
    id: "slipstream",
    name: "Slipstream",
    description: "Beginning an evasive dash grants 20% attack speed for 2.5 seconds.",
    stationarySecondsRequired: 0,
    bonusArmour: 0,
    postEvasiveAttackSpeedBonus: 0.2,
    postEvasiveAttackSpeedDurationSeconds: 2.5,
  },
  upgradeSlots: { offensive: 3, defensive: 1, support: 1, scavenger: 2 },
  startingWeaponId: "arc-carbine",
  startingWeaponName: "Arc Carbine",
  rackClasses: ["light", "light", "medium", "all"],
  levelGrowthDescription: "+2 SPEED / +1 DAMAGE / +1 LIGHT PROFICIENCY",
  unlockText: scoutUnlockRequirementText(),
  ultimate: {
    id: "deadeye-burst",
    name: "Deadeye Burst",
    description: "Fire three tightly grouped precision rounds that pierce two targets.",
    cooldownSeconds: 24,
    projectileCount: 3,
    projectileDamage: 7,
    explosionRadiusMetres: 0,
    projectileArcRadians: 0.12,
    projectileKnockbackMetres: 0.15,
    projectilePierceCount: 2,
  },
} satisfies HeroDefinition);
