import type { HeroDefinition } from "./HeroDefinition";

/** T4.9 mechanics candidate; presentation and deployment remain gated. */
export const TACTICIAN = Object.freeze({
  id: "tactician",
  displayName: "Tactician",
  role: "Battlefield control and target-priority specialist",
  baseMaxHealth: 11,
  baseRegenerationPerSecond: 0.05,
  movementSpeedMetresPerSecond: 4.85,
  collisionRadiusMetres: 0.54,
  evasiveMove: {
    presentation: "dash",
    durationSeconds: 0.46,
    distanceMetres: 3.6,
    invulnerabilitySeconds: 0.24,
  },
  defence: {
    armour: 1,
    flatDamageReduction: 0,
    maxShield: 0,
    shieldRechargeDelaySeconds: 3,
    shieldRechargePerSecond: 0.8,
    slowResistance: 0.1,
    attackSpeedMultiplier: 1,
    hitInvulnerabilitySeconds: 0.65,
  },
  weaponProficiencies: { light: 0, medium: 0, heavy: 0, unique: 0 },
  levelGrowth: {
    health: 1,
    armour: 1,
    damage: 0,
    speed: 0,
    supportEffect: 0,
    proficiency: { unique: 1 },
    alternatingPrimaryStats: ["damage", "speed"],
  },
  passive: {
    id: "designate-priority",
    name: "Designate Priority",
    description: "Enemies touched by Event Horizon are designated for 4 seconds; autonomous weapons prefer them.",
    stationarySecondsRequired: 0,
    bonusArmour: 0,
    designateDurationSeconds: 4,
  },
  upgradeSlots: { offensive: 2, defensive: 2, support: 2, scavenger: 1 },
  startingWeaponId: "event-horizon",
  startingWeaponName: "Event Horizon",
  rackClasses: ["unique", "light", "medium", "all"],
  levelGrowthDescription: "+1 HEALTH / +1 ARMOUR / +1 UNIQUE / ALTERNATE DAMAGE-SPEED",
  unlockText: "Mechanics review in progress; production presentation and clearance are not released.",
  ultimate: {
    id: "coordinated-strike",
    name: "Coordinated Strike",
    description: "Order every equipped weapon to perform one immediate attack toward its current target.",
    cooldownSeconds: 26,
    projectileCount: 0,
    projectileDamage: 0,
    explosionRadiusMetres: 0,
    coordinatedStrike: true,
  },
} satisfies HeroDefinition);
