/**
 * Shared arcade audio.
 *
 * Public API (unchanged):
 *   SnackPackAudio.play(name)      -- fire a sound by bare name, e.g. "place"
 *   SnackPackAudio.isMuted()
 *   SnackPackAudio.setMuted(bool)
 *   SnackPackAudio.preload(names)  -- optional warm-up, see below
 *
 * Sounds live at shared-assets/game-ui/audio/<name>.wav and are generated by
 * scripts/generate-arcade-audio.mjs in the monorepo. Available names:
 * place, pickup, invalid, success, win, tick, pop, whoosh.
 *
 * Three things this handles that a bare `new Audio(url).play()` does not:
 *
 *  1. **Pooling.** Creating an Audio element per call means a fresh network
 *     fetch (until the HTTP cache warms) and a fresh object to garbage-collect.
 *     Fine at one card placement per second; not fine for `pop` in Asteroid
 *     Destroyer, which can fire several times a frame. Each name keeps a small
 *     pool of reusable elements.
 *
 *  2. **Retrigger throttling.** Two hits in the same handful of milliseconds are
 *     inaudible as two events but sum in amplitude, so a burst gets *louder*
 *     rather than busier. A short per-name floor keeps that from happening.
 *
 *  3. **Autoplay-policy safety.** Browsers reject play() until the user has
 *     interacted with the page. Rejections are swallowed -- a missing sound
 *     effect must never surface as a console error or break game logic.
 *
 * Added for Pinball, and strictly additive -- the four-name API above is
 * untouched:
 *
 *   SnackPackAudio.bank(ns)        -- a namespaced player. bank("pinball")
 *                                     resolves "bumper-1" to
 *                                     .../audio/pinball/bumper-1.wav
 *   SnackPackAudio.loop(name)      -- a continuous sound with live controls,
 *                                     returning { setRate, setVolume, stop }
 *
 * Loops need a different mechanism from the one-shot pool: the pool exists to
 * hand out a FINISHED voice, and a loop never finishes. Pinball needs two of
 * them -- ball roll and ramp roll -- with volume and rate following the ball's
 * speed, which a fire-and-forget call cannot express.
 */
(function () {
  "use strict";

  var script = document.currentScript;
  var base = new URL(".", script ? script.src : window.location.href);
  var storageKey = "snackpack.arcade.audio.muted.v1";
  // Quiet by default. A player must explicitly opt in once; the preference is
  // then remembered for every arcade game.
  var muted = true;

  try {
    var savedMuted = localStorage.getItem(storageKey);
    muted = savedMuted == null ? true : savedMuted === "1";
  } catch (error) {}

  // Per-name pool of Audio elements, plus the timestamp of the last trigger.
  var pools = Object.create(null);
  var lastPlayed = Object.create(null);

  // Max simultaneous voices for one sound. Four is enough for overlapping
  // arcade hits without letting a runaway loop allocate without bound.
  var POOL_SIZE = 4;

  // Minimum gap between two triggers of the same sound. Below this they read as
  // one louder hit rather than two, so suppressing the second is closer to what
  // the player expects, not just cheaper.
  var RETRIGGER_MS = 35;

  // The UI set shipped as uncompressed PCM — 207 KB of WAV preloaded on every
  // game page, and win.wav alone was 99 KB of that. The same eight at MP3 96k
  // mono are 35 KB, and ffprobe puts every decoded duration within a
  // millisecond of the original, so even the 35ms tick keeps its attack rather
  // than picking up encoder padding. The .wav files stay as the fallback.
  var AUDIO_EXT = (function () {
    try {
      return new Audio().canPlayType("audio/mpeg") ? "mp3" : "wav";
    } catch (error) {
      return "wav";
    }
  }());

  function urlFor(name, ext) {
    return new URL("shared-assets/game-ui/audio/" + name + "." + (ext || AUDIO_EXT), base).href;
  }

  // One retry on the WAV if the MP3 is missing or refused, so a sound that
  // failed to encode degrades to the original rather than to silence.
  function withWavFallback(audio, name) {
    if (AUDIO_EXT === "wav") return audio;
    audio.addEventListener("error", function once() {
      audio.removeEventListener("error", once);
      audio.src = urlFor(name, "wav");
      audio.load();
    });
    return audio;
  }

  function poolFor(name) {
    if (!pools[name]) pools[name] = [];
    return pools[name];
  }

  function makeVoice(name) {
    var audio = withWavFallback(new Audio(urlFor(name)), name);
    audio.preload = "auto";
    audio.volume = 0.65;
    return audio;
  }

  function updateButtons() {
    document.querySelectorAll("[data-sp-audio-toggle]").forEach(function (button) {
      button.setAttribute("aria-pressed", muted ? "true" : "false");
      button.textContent = muted ? "Sound off" : "Sound on";
      button.title = muted ? "Turn game sounds on" : "Turn game sounds off";
    });
  }

  function setMuted(next) {
    muted = Boolean(next);
    try { localStorage.setItem(storageKey, muted ? "1" : "0"); } catch (error) {}
    updateButtons();
    // Loops are continuous, so muting has to reach the ones already running.
    for (var i = 0; activeLoops && i < activeLoops.length; i++) activeLoops[i]._sync();
  }

  /**
   * Fetch the files without playing them, so the first real hit is not delayed
   * by a network round trip. Safe to call with names already loaded.
   */
  function preload(names) {
    if (!names) return;
    if (typeof names === "string") names = [names];
    names.forEach(function (name) {
      var pool = poolFor(name);
      if (pool.length === 0) pool.push(makeVoice(name));
    });
  }

  function play(name, volume) {
    if (muted || !name) return;

    var now = (window.performance && performance.now) ? performance.now() : Date.now();
    if (lastPlayed[name] && now - lastPlayed[name] < RETRIGGER_MS) return;
    lastPlayed[name] = now;

    var pool = poolFor(name);

    // Prefer a voice that has finished. Reusing it avoids both the allocation
    // and a second fetch.
    var voice = null;
    for (var i = 0; i < pool.length; i++) {
      if (pool[i].ended || pool[i].paused) { voice = pool[i]; break; }
    }

    if (!voice) {
      if (pool.length < POOL_SIZE) {
        voice = makeVoice(name);
        pool.push(voice);
      } else {
        // All voices busy: steal the oldest rather than growing without bound.
        voice = pool[0];
      }
    }

    try {
      voice.currentTime = 0;
    } catch (error) {
      // Setting currentTime can throw if metadata has not loaded yet; playing
      // from wherever it is beats not playing at all.
    }

    voice.volume = Math.max(0, Math.min(1, volume == null ? 0.65 : volume));

    var promise = voice.play();
    if (promise && promise.catch) promise.catch(function () {});
  }

  // -- Loops ---------------------------------------------------------------
  // Tracked so muting can silence them: a loop started before the player
  // muted would otherwise keep running forever, which is the one failure the
  // one-shot pool cannot produce.
  var activeLoops = [];

  function loop(name) {
    // MP3 encoder delay is harmless for one-shots but makes a hard seam in a
    // loop. The Pinball rolling sounds and synchronized music beds therefore
    // use their canonical WAV deliveries directly.
    var seamless = /^pinball\/(?:ball-roll|ramp-roll|music\/)/.test(name);
    var audio = new Audio(urlFor(name, seamless ? "wav" : null));
    if (!seamless) withWavFallback(audio, name);
    audio.loop = true;
    audio.preload = "auto";
    audio.volume = 0;

    var wanted = 0;
    var stopped = false;

    var handle = {
      setVolume: function (v) {
        wanted = Math.max(0, Math.min(1, v || 0));
        if (!stopped) audio.volume = muted ? 0 : wanted;
        return handle;
      },
      setRate: function (r) {
        // Outside roughly 0.25-4 some browsers throw rather than clamp.
        try { audio.playbackRate = Math.max(0.25, Math.min(4, r || 1)); } catch (error) {}
        return handle;
      },
      stop: function () {
        stopped = true;
        try { audio.pause(); audio.currentTime = 0; } catch (error) {}
        var i = activeLoops.indexOf(handle);
        if (i >= 0) activeLoops.splice(i, 1);
        return handle;
      },
      /** Called by setMuted; not part of the public surface. */
      _sync: function () {
        if (stopped) return;
        audio.volume = muted ? 0 : wanted;
        if (muted) { try { audio.pause(); } catch (error) {} }
        else if (audio.paused) { var q = audio.play(); if (q && q.catch) q.catch(function () {}); }
      }
    };

    activeLoops.push(handle);
    if (!muted) { var promise = audio.play(); if (promise && promise.catch) promise.catch(function () {}); }
    return handle;
  }

  /**
   * A namespaced player, so a game with a bank of thirty-odd cues does not put
   * thirty-odd names into a module shared by every other game.
   */
  function bank(namespace) {
    var prefix = String(namespace || "").replace(/^\/+|\/+$/g, "");
    var at = function (name) { return prefix ? prefix + "/" + name : name; };
    var variantIndex = Object.create(null);
    return {
      play: function (name, volume) { play(at(name), volume); },
      loop: function (name) { return loop(at(name)); },
      preload: function (names) {
        if (typeof names === "string") names = [names];
        preload((names || []).map(at));
      },
      /** True round-robin across name-1..name-n, so chains stay varied. */
      playVariant: function (name, count, volume) {
        var n = Math.max(1, count || 1);
        var i = ((variantIndex[name] || 0) % n) + 1;
        variantIndex[name] = i;
        play(at(name + "-" + i), volume);
      }
    };
  }

  document.addEventListener("click", function (event) {
    var button = event.target.closest("[data-sp-audio-toggle]");
    if (button) setMuted(!muted);
  });
  document.addEventListener("DOMContentLoaded", updateButtons);

  window.SnackPackAudio = {
    isMuted: function () { return muted; },
    play: play,
    preload: preload,
    setMuted: setMuted,
    loop: loop,
    bank: bank
  };
})();
