/**
 * Shared arcade audio.
 *
 * Public API (unchanged):
 *   SnackPackAudio.play(name)      -- fire a sound by bare name, e.g. "place"
 *   SnackPackAudio.isMuted()
 *   SnackPackAudio.setMuted(bool)
 *   SnackPackAudio.preload(names)  -- optional warm-up, see below
 *
 * Sounds live at shared-assets/game-ui/audio/<name>.wav and are generated by
 * scripts/generate-arcade-audio.mjs in the monorepo. Available names:
 * place, pickup, invalid, success, win, tick, pop, whoosh.
 *
 * Three things this handles that a bare `new Audio(url).play()` does not:
 *
 *  1. **Pooling.** Creating an Audio element per call means a fresh network
 *     fetch (until the HTTP cache warms) and a fresh object to garbage-collect.
 *     Fine at one card placement per second; not fine for `pop` in Asteroid
 *     Destroyer, which can fire several times a frame. Each name keeps a small
 *     pool of reusable elements.
 *
 *  2. **Retrigger throttling.** Two hits in the same handful of milliseconds are
 *     inaudible as two events but sum in amplitude, so a burst gets *louder*
 *     rather than busier. A short per-name floor keeps that from happening.
 *
 *  3. **Autoplay-policy safety.** Browsers reject play() until the user has
 *     interacted with the page. Rejections are swallowed -- a missing sound
 *     effect must never surface as a console error or break game logic.
 */
(function () {
  "use strict";

  var script = document.currentScript;
  var base = new URL(".", script ? script.src : window.location.href);
  var storageKey = "snackpack.arcade.audio.muted.v1";
  var muted = false;

  try { muted = localStorage.getItem(storageKey) === "1"; } catch (error) {}

  // Per-name pool of Audio elements, plus the timestamp of the last trigger.
  var pools = Object.create(null);
  var lastPlayed = Object.create(null);

  // Max simultaneous voices for one sound. Four is enough for overlapping
  // arcade hits without letting a runaway loop allocate without bound.
  var POOL_SIZE = 4;

  // Minimum gap between two triggers of the same sound. Below this they read as
  // one louder hit rather than two, so suppressing the second is closer to what
  // the player expects, not just cheaper.
  var RETRIGGER_MS = 35;

  function urlFor(name) {
    return new URL("shared-assets/game-ui/audio/" + name + ".wav", base).href;
  }

  function poolFor(name) {
    if (!pools[name]) pools[name] = [];
    return pools[name];
  }

  function makeVoice(name) {
    var audio = new Audio(urlFor(name));
    audio.preload = "auto";
    audio.volume = 0.65;
    return audio;
  }

  function updateButtons() {
    document.querySelectorAll("[data-sp-audio-toggle]").forEach(function (button) {
      button.setAttribute("aria-pressed", muted ? "true" : "false");
      button.textContent = muted ? "Sound off" : "Sound on";
      button.title = muted ? "Turn game sounds on" : "Turn game sounds off";
    });
  }

  function setMuted(next) {
    muted = Boolean(next);
    try { localStorage.setItem(storageKey, muted ? "1" : "0"); } catch (error) {}
    updateButtons();
  }

  /**
   * Fetch the files without playing them, so the first real hit is not delayed
   * by a network round trip. Safe to call with names already loaded.
   */
  function preload(names) {
    if (!names) return;
    if (typeof names === "string") names = [names];
    names.forEach(function (name) {
      var pool = poolFor(name);
      if (pool.length === 0) pool.push(makeVoice(name));
    });
  }

  function play(name) {
    if (muted || !name) return;

    var now = (window.performance && performance.now) ? performance.now() : Date.now();
    if (lastPlayed[name] && now - lastPlayed[name] < RETRIGGER_MS) return;
    lastPlayed[name] = now;

    var pool = poolFor(name);

    // Prefer a voice that has finished. Reusing it avoids both the allocation
    // and a second fetch.
    var voice = null;
    for (var i = 0; i < pool.length; i++) {
      if (pool[i].ended || pool[i].paused) { voice = pool[i]; break; }
    }

    if (!voice) {
      if (pool.length < POOL_SIZE) {
        voice = makeVoice(name);
        pool.push(voice);
      } else {
        // All voices busy: steal the oldest rather than growing without bound.
        voice = pool[0];
      }
    }

    try {
      voice.currentTime = 0;
    } catch (error) {
      // Setting currentTime can throw if metadata has not loaded yet; playing
      // from wherever it is beats not playing at all.
    }

    var promise = voice.play();
    if (promise && promise.catch) promise.catch(function () {});
  }

  document.addEventListener("click", function (event) {
    var button = event.target.closest("[data-sp-audio-toggle]");
    if (button) setMuted(!muted);
  });
  document.addEventListener("DOMContentLoaded", updateButtons);

  window.SnackPackAudio = {
    isMuted: function () { return muted; },
    play: play,
    preload: preload,
    setMuted: setMuted
  };
})();
