import fs from "node:fs/promises";
import path from "node:path";

/*
 * Normalizes the primary header nav across every page so the top-right header
 * is identical site-wide. Replaces the contents of <nav aria-label="Primary">
 * with the canonical link set, using absolute (/-rooted) URLs so it works at
 * any folder depth. Run: node scripts/normalize-nav.mjs
 *
 * The World Cup group/team pages are generated by build-world-cup.mjs, whose
 * template carries the same canonical nav — keep the two in sync.
 */

const root = path.resolve(".");
const NAV_RE = /([ \t]*)<nav aria-label="Primary">[\s\S]*?<\/nav>/;

function canonicalNav(indent) {
  const i1 = indent + "  ";
  const i2 = indent + "    ";
  return [
    `<nav aria-label="Primary">`,
    `${i1}<ul class="nav-links">`,
    `${i2}<li><a href="/apps/">Apps</a></li>`,
    `${i2}<li><a href="/play/">Play</a></li>`,
    `${i2}<li><a href="/guides/">Guides</a></li>`,
    `${i2}<li><a class="nav-wc" href="/world-cup/"><img class="nav-ball" src="/world-cup/officialball_transparent2-50.png" alt="" width="18" height="18">World Cup</a></li>`,
    `${i2}<li><a href="/#pipeline">Roadmap</a></li>`,
    `${i2}<li><a href="/privacy/">Privacy</a></li>`,
    `${i2}<li><a href="/terms/">Terms</a></li>`,
    `${i2}<li><a class="pill-link" href="mailto:support@snackpackuniverse.com">Support</a></li>`,
    `${i1}</ul>`,
    `${indent}</nav>`
  ].join("\n");
}

async function* htmlFiles(dir) {
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* htmlFiles(full);
    else if (entry.isFile() && entry.name.endsWith(".html")) yield full;
  }
}

async function main() {
  let changed = 0;
  let skipped = 0;
  const noNav = [];

  for await (const file of htmlFiles(root)) {
    const original = await fs.readFile(file, "utf8");
    if (!NAV_RE.test(original)) {
      noNav.push(path.relative(root, file));
      continue;
    }
    const updated = original.replace(NAV_RE, (m, indent) => indent + canonicalNav(indent));
    if (updated !== original) {
      await fs.writeFile(file, updated, "utf8");
      changed += 1;
    } else {
      skipped += 1;
    }
  }

  console.log(`Updated ${changed} pages, ${skipped} already canonical.`);
  if (noNav.length) console.log(`No primary nav (skipped): ${noNav.join(", ")}`);
}

main().catch((error) => { console.error(error); process.exit(1); });
