/**
 * game.js -- loop, input, and arcade integration.
 *
 * Routing only. The engine owns physics, rules.js owns scoring, and this file
 * owns input, timing and the DOM -- it hands every engine event to the ruleset
 * and executes the commands the ruleset asks for. It deliberately contains no
 * scoring logic of its own.
 *
 * The engine never reads a clock; this file owns all of the timing.
 */

import { createWorld, advance, drainEvents, serveBall, nudge, addBall, releaseSaucer, DT } from './engine.js?v=fb49d14d4e';
import { createRenderer } from './render.js?v=fb49d14d4e';
import { MODES, SAUCERS, BUMPERS } from './table.js?v=fb49d14d4e';

/** Slingshot face midpoints, for spark positions. */
const SLING_POS = {
  'sling-left': { x: 108, y: 800 },
  'sling-right': { x: 378, y: 800 },
};
import {
  createRules, applyEvent, tick as tickRules, nextBall, setBallsInPlay,
  drainCommands, drainLog, statusLine, litShots,
  serialize as serializeRules, deserialize as deserializeRules,
  RANKS, MISSIONS,
} from './rules.js?v=fb49d14d4e';

/** ?daily=YYYY-MM-DD -- everyone gets the same missions, one attempt. */
const DAILY = new URLSearchParams(location.search).get('daily');

/**
 * ?record=1 -- capture a replay tape of this game.
 *
 * Records (dt, buttons) per FRAME, not per simulation step, because that is
 * what makes a real game reproducible: `advance()` is deterministic given the
 * same dt sequence and the same inputs, so replaying the recorded frames
 * reproduces the run exactly -- including the frame jitter of however the
 * machine happened to be running at the time. A tape recorded by a person
 * covers shot patterns and hesitation no scripted flipper loop will find.
 *
 * Play a game with ?record=1, then in the console:
 *     copy(JSON.stringify(window.__pbTape()))
 * and save it as tools/pinball/tapes/<name>.json.
 *
 * Costs nothing when the flag is absent: the array is never allocated.
 */
const RECORD = new URLSearchParams(location.search).has('record');
const TAPE_FRAME_CAP = 60 * 60 * 6; // ~6 minutes; a tape is not a memory leak

/**
 * Audio. Names resolve under shared-assets/game-ui/audio/pinball/ and are
 * generated by Codex per docs/pinball/05-codex-art-brief.md. Until they land
 * every call is a silent miss, which audio.js swallows by design -- a missing
 * effect must never surface as an error or change game logic.
 */
const SFX = window.SnackPackAudio ? window.SnackPackAudio.bank('pinball') : null;
const sfx = (name) => { if (SFX) SFX.play(name); };
const sfxVariant = (name, n) => { if (SFX) SFX.playVariant(name, n); };

/** Event -> one-shot cue. Kept as data so the bank and the engine stay in step. */
const EVENT_SFX = {
  'target': 'drop-target',
  'target-bank-clear': 'drop-bank-clear',
  'rollover': 'gate',
  'saucer': 'saucer-in',
  'saucer-kick': 'saucer-kick',
  'ramp-enter': 'gate',
  'ramp-reject': 'post-1',
  'kickback': 'kickback',
  'drain': 'ball-drain',
  'plunge': 'plunger-release',
  'tilt-warn': 'tilt-warn',
  'tilt': 'tilt',
  'spinner': 'spinner-tick',
};

const el = (id) => document.getElementById(id);

const state = {
  world: null,
  rules: null,
  renderer: null,
  mode: 'classic',
  ballsLeft: 3,
  pendingKicks: [],
  running: false,
  paused: false,
  last: 0,
  flashes: new Map(),
  input: { left: false, right: false, plunge: false },
  lit: [],
  resume: null,
  seed: 0,
  tape: null,
  roll: null,
  rampRoll: null,
  music: null,
  musicName: null,
  raf: 0,
};

// ---------------------------------------------------------------------------
// Loop
// ---------------------------------------------------------------------------

function frame(now) {
  state.raf = requestAnimationFrame(frame);
  if (!state.world) return;

  const dt = state.last ? Math.min((now - state.last) / 1000, 0.25) : 0;
  state.last = now;

  if (state.running && !state.paused) {
    if (state.tape && state.tape.length < TAPE_FRAME_CAP) {
      // Round dt so the tape is stable JSON rather than full float noise; the
      // engine is fed the rounded value too, so replay matches exactly.
      const d = Math.round(dt * 100000) / 100000;
      const buttons = (state.input.left ? 1 : 0) | (state.input.right ? 2 : 0) | (state.input.plunge ? 4 : 0);
      state.tape.push([d, buttons]);
      advance(state.world, state.input, d);
    } else {
      advance(state.world, state.input, dt);
    }
    handleEvents(drainEvents(state.world));
    tickRules(state.rules, dt);
    runCommands(drainCommands(state.rules));
    runPendingKicks(dt);
    setBallsInPlay(state.rules, state.world.ballsInPlay);
    showLog(drainLog(state.rules));
    state.lit = litShots(state.rules);
    updateRollSound();
    if (state.resume) state.resume.changed();
    paint();
  }

  // Decay bumper flashes on real time, not on simulation steps, so they look
  // the same whether the tab is running fast or catching up.
  for (const [k, v] of state.flashes) {
    const next = v - dt;
    if (next <= 0) state.flashes.delete(k); else state.flashes.set(k, next);
  }

  state.renderer.draw(state.world, state.flashes, state.lit, dt);
}

function handleEvents(events) {
  for (const e of events) {
    // Feedback for the hit, before the ruleset decides what it is worth.
    if (e.type === 'bumper') {
      state.flashes.set(e.id, 0.12);
      const b = BUMPERS.find((x) => x.id === e.id);
      if (b) state.renderer.burst(b.x, b.y, 8, '255,226,170', 260);
      state.renderer.kick(2.6);
    } else if (e.type === 'sling') {
      state.flashes.set(e.id, 0.10);
      const w = SLING_POS[e.id];
      if (w) state.renderer.burst(w.x, w.y, 6, '255,190,150', 230);
      state.renderer.kick(2.0);
    }
    if (e.type === 'target') state.renderer.kick(1.2);

    // Round-robin variants so a bumper chain sounds busy rather than like a
    // machine gun. audio.js throttles retriggers; variants are the other half.
    if (e.type === 'bumper') sfxVariant('bumper', 3);
    else if (e.type === 'sling') sfxVariant('sling', 2);
    else if (e.type === 'post') sfxVariant('post', 2);
    else if (EVENT_SFX[e.type]) sfx(EVENT_SFX[e.type]);

    // The ruleset owns all scoring. This file only routes.
    applyEvent(state.rules, e);

    if (e.type === 'ball-lost') onBallLost();
    if (e.type === 'escaped') {
      // Should never happen. If it does it is a physics bug, and it must be
      // loud rather than quietly recovered from.
      console.warn('pinball: ball escaped the cabinet', e);
    }
  }
}

/**
 * rules.js is pure and cannot touch the world, so it emits commands instead.
 * This is the only place they are executed.
 */
function runCommands(commands) {
  for (const c of commands) {
    switch (c.type) {
      case 'release-saucer':
        if (c.delay) state.pendingKicks.push({ id: c.id, t: c.delay });
        else releaseSaucer(state.world, c.id);
        break;
      case 'celebrate':
        state.renderer.kick(5);
        break;
      case 'add-balls': {
        const from = SAUCERS.find((x) => x.id === 'lock') || { x: 408, y: 330 };
        for (let i = 0; i < c.count; i += 1) {
          addBall(state.world, from.x, from.y + i * 4, -260 - i * 40, 700);
        }
        break;
      }
      // Audio arrives at P5. Routing the cues now keeps the wiring honest: if
      // one is missing then, it will be missing HERE rather than never having
      // been emitted in the first place.
      case 'sound':
      case 'voice':
        sfx(c.name);
        break;
      case 'music':
        setMusic(c.bed);
        break;
      default:
        break;
    }
  }
}

// -- Continuous sound ------------------------------------------------------
// Ball roll and the music bed are loops, which the one-shot pool cannot do:
// it hands out a FINISHED voice, and a loop never finishes.

function setMusic(bed) {
  if (!SFX) return;
  const want = bed === 'intense' ? 'music/bed-intense' : 'music/bed-calm';
  if (state.musicName === want) return;
  if (state.music) state.music.stop();
  state.musicName = want;
  state.music = SFX.loop(want.replace('music/', 'music/'));
  state.music.setVolume(0.25);
}

/** Roll volume and pitch follow the fastest ball, so the table sounds alive. */
function updateRollSound() {
  if (!SFX) return;
  const balls = state.world.balls.filter((b) => b.alive && !b.captured);
  const fastest = balls.reduce((m, b) => Math.max(m, Math.hypot(b.vx, b.vy)), 0);
  const onRamp = balls.some((b) => b.inRamp);

  if (!state.roll) {
    state.roll = SFX.loop('ball-roll');
    state.rampRoll = SFX.loop('ramp-roll');
    state.rampRoll.setVolume(0);
  }
  const n = Math.min(fastest / 2200, 1);
  state.roll.setVolume(onRamp ? 0 : 0.30 * n).setRate(0.7 + n * 0.8);
  state.rampRoll.setVolume(onRamp ? 0.30 : 0);
}

function stopContinuous() {
  if (state.roll) { state.roll.stop(); state.roll = null; }
  if (state.rampRoll) { state.rampRoll.stop(); state.rampRoll = null; }
  if (state.music) { state.music.stop(); state.music = null; state.musicName = null; }
}

function runPendingKicks(dt) {
  if (!state.pendingKicks.length) return;
  for (const k of state.pendingKicks) k.t -= dt;
  const due = state.pendingKicks.filter((k) => k.t <= 0);
  state.pendingKicks = state.pendingKicks.filter((k) => k.t > 0);
  for (const k of due) releaseSaucer(state.world, k.id);
}

function showLog(entries) {
  for (const entry of entries) announce(entry.text);
}

function onBallLost() {
  if (state.world.mode.endless) {
    serveBall(state.world);
    return;
  }
  const bonus = nextBall(state.rules);
  state.ballsLeft -= 1;
  if (state.ballsLeft <= 0) {
    gameOver();
    return;
  }
  serveBall(state.world);
  state.pendingKicks = [];
  announce(bonus > 0 ? `Bonus ${bonus.toLocaleString()}` : `Ball ${state.rules.ball}`);
  paint();
}

function gameOver() {
  state.running = false;
  stopContinuous();
  sfx('game-over');
  const r = state.rules;
  announce(`Game over. ${r.score.toLocaleString()} points.`);
  el('pb-overlay').hidden = false;
  el('pb-overlay-title').textContent = 'Game over';
  el('pb-overlay-body').textContent = `${r.score.toLocaleString()} points`;
  el('pb-overlay-note').textContent =
    `${RANKS[r.rank]} • ${r.missionsDone.length} of ${MISSIONS.length} missions`;
  saveBest();
  if (state.resume) state.resume.clear();
  if (DAILY) markDailyDone();
  offerShare();
}

/**
 * Share on game over. The spoiler rule matters even here: the mission ORDER is
 * the daily's content, so the card reports how far you got, never which
 * missions came up.
 */
function offerShare() {
  if (!window.SnackPackShare) return;
  const r = state.rules;
  const filled = Math.min(r.missionsDone.length, MISSIONS.length);
  const row = '\u{1F7E9}'.repeat(filled) + '\u2B1C'.repeat(MISSIONS.length - filled);
  window.SnackPackShare.result({
    mount: document.querySelector('.pb-stage'),
    game: 'Pinball',
    puzzle: DAILY || undefined,
    headline: `${MODES[state.mode].label}: ${r.score.toLocaleString()} as ${RANKS[r.rank]}`,
    stats: [`${r.missionsDone.length}/${MISSIONS.length} missions`, `ball ${r.ball}`],
    grid: [row],
  });
}

const dailyKey = () => `pinball_daily_${DAILY}`;

function dailyAlreadyPlayed() {
  if (!DAILY) return false;
  try {
    if (window.SnackPackStore) return !!window.SnackPackStore.get('pinball', 'daily', DAILY);
    return !!localStorage.getItem(`sp_${dailyKey()}`);
  } catch (err) { return false; }
}

function markDailyDone() {
  try {
    const v = String(state.rules.score);
    if (window.SnackPackStore) window.SnackPackStore.set('pinball', 'daily', DAILY, v);
    else localStorage.setItem(`sp_${dailyKey()}`, v);
  } catch (err) { /* storage can be blocked; never break the game over it */ }
}

// ---------------------------------------------------------------------------
// Persistence -- arcade convention, sp_-prefixed via SnackPackStore
// ---------------------------------------------------------------------------

const bestKey = () => `pinball_best_${state.mode}`;

function readBest() {
  try {
    if (window.SnackPackStore) return Number(window.SnackPackStore.get('pinball', 'best', state.mode)) || 0;
    return Number(localStorage.getItem(`sp_${bestKey()}`)) || 0;
  } catch (err) { return 0; }
}

function saveBest() {
  try {
    if (state.rules.score <= readBest()) return;
    if (window.SnackPackStore) window.SnackPackStore.set('pinball', 'best', state.mode, state.rules.score);
    else localStorage.setItem(`sp_${bestKey()}`, String(state.rules.score));
  } catch (err) { /* storage can be blocked; never break the game over it */ }
}

// ---------------------------------------------------------------------------
// UI
// ---------------------------------------------------------------------------

function paint() {
  const r = state.rules;
  el('pb-score').textContent = r ? r.score.toLocaleString() : '0';
  el('pb-ball').textContent = state.world && state.world.mode.endless
    ? '∞'
    : `${r ? r.ball : 1} / ${MODES[state.mode].balls}`;
  el('pb-best').textContent = readBest().toLocaleString();
  el('pb-rank').textContent = r ? RANKS[r.rank] : RANKS[0];
  if (r) el('pb-dmd').textContent = statusLine(r);
}

let announceTimer = 0;
function announce(text) {
  const live = el('pb-live');
  live.textContent = text;
  const banner = el('pb-banner');
  banner.textContent = text;
  banner.hidden = false;
  clearTimeout(announceTimer);
  announceTimer = setTimeout(() => { banner.hidden = true; }, 1600);
}

function describeTable() {
  if (!state.world || !state.rules) return 'Pinball table';
  const b = state.world.balls.find((x) => x.alive);
  if (!b || !state.rules) return 'Pinball table, ball lost';
  const where = b.y < 300 ? 'the top arch' : b.y < 700 ? 'the middle of the table' : 'near the flippers';
  const r = state.rules;
  return `Pinball. Score ${r.score}. Ball ${r.ball}. ${statusLine(r)}. Ball is at ${where}.`;
}

// ---------------------------------------------------------------------------
// Start / mode select
// ---------------------------------------------------------------------------

function start(modeId) {
  if (DAILY && dailyAlreadyPlayed()) {
    announce("Today's challenge is already played. Come back tomorrow.");
    return;
  }
  state.mode = modeId;
  const seed = seedForRun();
  state.seed = seed;
  state.world = createWorld(modeId, seed);
  state.rules = createRules(seed, modeId);
  state.tape = RECORD ? [] : null;
  state.ballsLeft = MODES[modeId].balls;
  state.pendingKicks = [];
  state.running = true;
  state.paused = false;
  state.flashes.clear();
  el('pb-overlay').hidden = true;
  el('pb-modes').hidden = true;
  el('pb-hud').hidden = false;
  state.renderer.resize();
  setMusic('calm');
  paint();
  announce(`${MODES[modeId].label}. Hold the plunger.`);
}

/** Daily runs share a seed, so everyone gets the same missions in the same order. */
function seedForRun() {
  if (DAILY) {
    let h = 2166136261;
    for (let i = 0; i < DAILY.length; i += 1) {
      h ^= DAILY.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return h >>> 0;
  }
  return (Date.now() ^ Math.floor(Math.random() * 0xffffffff)) >>> 0;
}

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

const KEYS_LEFT = ['KeyZ', 'ArrowLeft', 'ShiftLeft'];
const KEYS_RIGHT = ['Slash', 'ArrowRight', 'ShiftRight'];

/**
 * Flipper sound follows the BUTTON, not the ball. A flipper makes its noise
 * whether or not it hits anything, and up and down are different samples --
 * one shared flipper sound is the commonest tell of an amateur pinball game.
 */
function flipperSound(down) {
  sfx(down ? 'flipper-up' : 'flipper-down');
}

function bindKeys() {
  window.addEventListener('keydown', (e) => {
    if (e.repeat) return;
    if (KEYS_LEFT.includes(e.code)) { state.input.left = true; flipperSound(true); e.preventDefault(); }
    else if (KEYS_RIGHT.includes(e.code)) { state.input.right = true; flipperSound(true); e.preventDefault(); }
    else if (e.code === 'Space') { state.input.plunge = true; e.preventDefault(); }
    else if (e.code === 'Comma' && state.world) nudge(state.world, -1, 0);
    else if (e.code === 'Period' && state.world) nudge(state.world, 1, 0);
    else if (e.code === 'KeyN' && state.world) nudge(state.world, 0, -1);
  });
  window.addEventListener('keyup', (e) => {
    if (KEYS_LEFT.includes(e.code)) { state.input.left = false; flipperSound(false); }
    else if (KEYS_RIGHT.includes(e.code)) { state.input.right = false; flipperSound(false); }
    else if (e.code === 'Space') state.input.plunge = false;
  });
}

/**
 * Touch: full-height columns, not buttons near the flippers -- a player's
 * thumbs rest at the bottom of a phone, and both flippers at once is not
 * optional in pinball, so each pointer is tracked by id.
 *
 * Coordinates come from getBoundingClientRect, never pageX. Brain Games has a
 * live defect from exactly that: pageX breaks under a transformed game area.
 */
function bindTouch(stage) {
  const zones = new Map();

  const zoneFor = (clientX) => {
    const r = stage.getBoundingClientRect();
    const f = (clientX - r.left) / r.width;
    if (f < 0.34) return 'left';
    if (f > 0.66) return 'right';
    return 'plunge';
  };

  const apply = () => {
    const active = new Set(zones.values());
    const wasLeft = state.input.left;
    const wasRight = state.input.right;
    state.input.left = active.has('left');
    state.input.right = active.has('right');
    state.input.plunge = active.has('plunge');
    if (state.input.left !== wasLeft) flipperSound(state.input.left);
    if (state.input.right !== wasRight) flipperSound(state.input.right);
  };

  stage.addEventListener('pointerdown', (e) => {
    // Anything interactive inside the stage -- the mode buttons, the game-over
    // button -- must keep working. Capturing the pointer and calling
    // preventDefault here swallows the click before it ever reaches them, so a
    // player simply could not start a game by tapping. Bail out early instead.
    if (e.target.closest('button, a, [role="button"]')) return;
    if (!state.running) return;

    stage.setPointerCapture(e.pointerId);
    zones.set(e.pointerId, zoneFor(e.clientX));
    apply();
    e.preventDefault();
  });
  const release = (e) => { zones.delete(e.pointerId); apply(); };
  stage.addEventListener('pointerup', release);
  stage.addEventListener('pointercancel', release);
  stage.addEventListener('pointerleave', release);
}

// ---------------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------------

function boot() {
  const canvas = el('pb-canvas');
  const stage = canvas.parentElement;
  state.renderer = createRenderer(canvas);
  state.world = createWorld('classic', 1);

  bindKeys();
  bindTouch(stage);
  window.addEventListener('resize', () => state.renderer.resize());

  for (const btn of document.querySelectorAll('[data-mode]')) {
    btn.addEventListener('click', () => start(btn.dataset.mode));
  }
  el('pb-again').addEventListener('click', () => {
    el('pb-overlay').hidden = true;
    el('pb-modes').hidden = false;
    el('pb-hud').hidden = true;
    state.running = false;
  });

  // Shared arcade pause. It stops the accumulator; rAF keeps running so the
  // table stays painted.
  if (window.SnackPackPause) {
    window.SnackPackPause.attach({
      mount: document.querySelector('.pb-controls'),
      stage,
      isPlaying: () => state.running && !state.paused,
      pause: () => { state.paused = true; },
      resume: () => { state.paused = false; state.last = 0; },
    });
  }

  // Saved progress. The world itself is NOT serialised: restoring a ball
  // mid-flight would drop the player into a physics state they did not
  // create, mid-air and mid-shot. Resuming instead returns the ball to the
  // plunger with the score, rank, missions and ball number intact -- which is
  // what a real machine does when the power comes back.
  if (window.SnackPackResume) {
    state.resume = window.SnackPackResume.attach({
      game: 'pinball',
      variant: () => state.mode,
      schemaVersion: 1,
      serialize: () => ({
        mode: state.mode,
        ballsLeft: state.ballsLeft,
        rules: serializeRules(state.rules),
      }),
      validate: (p) => !!p && typeof p.mode === 'string' && !!p.rules
        && typeof p.rules.score === 'number',
      restore: (p) => {
        state.mode = p.mode;
        state.rules = deserializeRules(p.rules);
        state.world = createWorld(p.mode, state.rules.seed);
        state.ballsLeft = p.ballsLeft;
        state.pendingKicks = [];
        state.running = true;
        state.paused = false;
        el('pb-modes').hidden = true;
        el('pb-overlay').hidden = true;
        el('pb-hud').hidden = false;
        state.renderer.resize();
        state.lit = litShots(state.rules);
        paint();
        announce('Resumed');
        return true;
      },
      isActive: () => state.running && state.rules && state.rules.score > 0,
    });
  }

  // Keep the accessible description current without touching it every frame.
  setInterval(() => { canvas.setAttribute('aria-label', describeTable()); }, 1200);

  paint();
  state.raf = requestAnimationFrame(frame);
}

if (RECORD) {
  window.__pbTape = () => ({
    kind: 'frames',
    name: `human-${state.mode}-${state.seed}`,
    seed: state.seed,
    mode: state.mode,
    frames: state.tape || [],
  });
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
else boot();
