/**
 * game.js -- loop, input, and arcade integration.
 *
 * Routing only. The engine owns physics, rules.js owns scoring, and this file
 * owns input, timing and the DOM -- it hands every engine event to the ruleset
 * and executes the commands the ruleset asks for. It deliberately contains no
 * scoring logic of its own.
 *
 * The engine never reads a clock; this file owns all of the timing.
 */

import { createWorld, advance, drainEvents, serveBall, nudge, addBall, releaseSaucer, DT } from './engine.js?v=ee8b9ec348';
import { createRenderer } from './render.js?v=ee8b9ec348';
import { MODES, SAUCERS, BUMPERS } from './table.js?v=ee8b9ec348';

/** Slingshot face midpoints, for spark positions. */
const SLING_POS = {
  'sling-left': { x: 108, y: 800 },
  'sling-right': { x: 378, y: 800 },
};
import {
  createRules, applyEvent, tick as tickRules, nextBall, setBallsInPlay,
  drainCommands, drainLog, statusLine, litShots,
  serialize as serializeRules, deserialize as deserializeRules,
  RANKS, MISSIONS, COMBO_WINDOW,
  armBallSave, consumeBallSave, consumeExtraBall,
} from './rules.js?v=ee8b9ec348';

/** ?daily=YYYY-MM-DD -- everyone gets the same missions, one attempt. */
const DAILY = new URLSearchParams(location.search).get('daily');

/**
 * ?record=1 -- capture a replay tape of this game.
 *
 * Records (dt, buttons) per FRAME, not per simulation step, because that is
 * what makes a real game reproducible: `advance()` is deterministic given the
 * same dt sequence and the same inputs, so replaying the recorded frames
 * reproduces the run exactly -- including the frame jitter of however the
 * machine happened to be running at the time. A tape recorded by a person
 * covers shot patterns and hesitation no scripted flipper loop will find.
 *
 * Play a game with ?record=1, then in the console:
 *     copy(JSON.stringify(window.__pbTape()))
 * and save it as tools/pinball/tapes/<name>.json.
 *
 * Costs nothing when the flag is absent: the array is never allocated.
 */
const RECORD = new URLSearchParams(location.search).has('record');
const TAPE_FRAME_CAP = 60 * 60 * 6; // ~6 minutes; a tape is not a memory leak

/**
 * Audio. Names resolve under shared-assets/game-ui/audio/pinball/ and are
 * generated by Codex per docs/pinball/05-codex-art-brief.md. Until they land
 * every call is a silent miss, which audio.js swallows by design -- a missing
 * effect must never surface as an error or change game logic.
 */
const SFX = window.SnackPackAudio ? window.SnackPackAudio.bank('pinball') : null;
const CUE_GAIN = {
  'spinner-tick': 0.55, 'post-1': 0.60, 'post-2': 0.60,
  'game-over': 0.80, 'tilt-warn': 0.80, tilt: 0.90,
};
function gainFor(name) {
  if (CUE_GAIN[name] != null) return CUE_GAIN[name];
  if (name.startsWith('voice/')) return 0.90;
  if (/^(bumper|sling|post)-/.test(name)) return 0.65;
  if (/^(skill-shot|combo-|mission-complete|jackpot|super-jackpot|rank-up|multiball|wizard)/.test(name)) return 0.95;
  if (/^(mission-|tilt|game-over)/.test(name)) return 0.80;
  return 0.70;
}
const sfx = (name) => { if (SFX) SFX.play(name, gainFor(name)); };
const sfxVariant = (name, n) => { if (SFX) SFX.playVariant(name, n, gainFor(`${name}-1`)); };

/** Event -> one-shot cue. Kept as data so the bank and the engine stay in step. */
const EVENT_SFX = {
  'target': 'drop-target',
  'target-bank-clear': 'drop-bank-clear',
  'rollover': 'gate',
  'saucer': 'saucer-in',
  'saucer-kick': 'saucer-kick',
  'ramp-enter': 'gate',
  'ramp-reject': 'post-1',
  'kickback': 'kickback',
  'drain': 'ball-drain',
  'plunge': 'plunger-release',
  'tilt-warn': 'tilt-warn',
  'tilt': 'tilt',
  'spinner': 'spinner-tick',
};

const el = (id) => document.getElementById(id);

const state = {
  world: null,
  rules: null,
  renderer: null,
  mode: 'classic',
  ballsLeft: 3,
  pendingKicks: [],
  running: false,
  paused: false,
  rolling: false,        // the end-of-ball bonus owns the score display
  last: 0,
  flashes: new Map(),
  input: { left: false, right: false, plunge: false },
  lit: [],
  resume: null,
  seed: 0,
  tape: null,
  roll: null,
  rampRoll: null,
  musicCalm: null,
  musicIntense: null,
  musicBed: 'calm',
  musicVolumes: { calm: 0, intense: 0 },
  musicFade: 0,
  raf: 0,
};

// ---------------------------------------------------------------------------
// Loop
// ---------------------------------------------------------------------------

function frame(now) {
  state.raf = requestAnimationFrame(frame);
  if (!state.world) return;

  const dt = state.last ? Math.min((now - state.last) / 1000, 0.25) : 0;
  state.last = now;

  if (state.running && !state.paused) {
    if (state.tape && state.tape.length < TAPE_FRAME_CAP) {
      // Round dt so the tape is stable JSON rather than full float noise; the
      // engine is fed the rounded value too, so replay matches exactly.
      const d = Math.round(dt * 100000) / 100000;
      const buttons = (state.input.left ? 1 : 0) | (state.input.right ? 2 : 0) | (state.input.plunge ? 4 : 0);
      state.tape.push([d, buttons]);
      advance(state.world, state.input, d);
    } else {
      advance(state.world, state.input, dt);
    }
    handleEvents(drainEvents(state.world));
    tickRules(state.rules, dt);
    runCommands(drainCommands(state.rules));
    runPendingKicks(dt);
    setBallsInPlay(state.rules, state.world.ballsInPlay);
    showLog(drainLog(state.rules));
    state.lit = litShots(state.rules);
    updateRollSound();
    if (state.resume) state.resume.changed();
    paint();
  }

  // Decay bumper flashes on real time, not on simulation steps, so they look
  // the same whether the tab is running fast or catching up.
  for (const [k, v] of state.flashes) {
    const next = v - dt;
    if (next <= 0) state.flashes.delete(k); else state.flashes.set(k, next);
  }

  state.renderer.draw(state.world, state.flashes, state.lit, dt);
}

function handleEvents(events) {
  for (const e of events) {
    // Feedback for the hit, before the ruleset decides what it is worth.
    if (e.type === 'bumper') {
      state.flashes.set(e.id, 0.12);
      const b = BUMPERS.find((x) => x.id === e.id);
      if (b) state.renderer.burst(b.x, b.y, 8, '255,226,170', 260);
      state.renderer.kick(2.6);
    } else if (e.type === 'sling') {
      state.flashes.set(e.id, 0.10);
      const w = SLING_POS[e.id];
      if (w) state.renderer.burst(w.x, w.y, 6, '255,190,150', 230);
      state.renderer.kick(2.0);
    }
    if (e.type === 'target') state.renderer.kick(1.2);

    // Round-robin variants so a bumper chain sounds busy rather than like a
    // machine gun. audio.js throttles retriggers; variants are the other half.
    if (e.type === 'bumper') sfxVariant('bumper', 3);
    else if (e.type === 'sling') sfxVariant('sling', 2);
    else if (e.type === 'post') sfxVariant('post', 2);
    else if (EVENT_SFX[e.type]) sfx(EVENT_SFX[e.type]);

    // The ruleset owns all scoring. This file only routes.
    applyEvent(state.rules, e);

    if (e.type === 'ball-lost') onBallLost();
    if (e.type === 'escaped') {
      // Should never happen. If it does it is a physics bug, and it must be
      // loud rather than quietly recovered from.
      console.warn('pinball: ball escaped the cabinet', e);
    }
  }
}

/**
 * rules.js is pure and cannot touch the world, so it emits commands instead.
 * This is the only place they are executed.
 */
function runCommands(commands) {
  for (const c of commands) {
    switch (c.type) {
      case 'release-saucer':
        if (c.delay) state.pendingKicks.push({ id: c.id, t: c.delay });
        else releaseSaucer(state.world, c.id);
        break;
      case 'celebrate':
        state.renderer.kick(5);
        break;
      case 'add-balls': {
        const from = SAUCERS.find((x) => x.id === 'lock') || { x: 408, y: 330 };
        for (let i = 0; i < c.count; i += 1) {
          addBall(state.world, from.x, from.y + i * 4, -260 - i * 40, 700);
        }
        break;
      }
      // Audio arrives at P5. Routing the cues now keeps the wiring honest: if
      // one is missing then, it will be missing HERE rather than never having
      // been emitted in the first place.
      case 'sound':
      case 'voice':
        sfx(c.name);
        break;
      case 'music':
        setMusic(c.bed);
        break;
      default:
        break;
    }
  }
}

// -- Continuous sound ------------------------------------------------------
// Ball roll and the music bed are loops, which the one-shot pool cannot do:
// it hands out a FINISHED voice, and a loop never finishes.

function setMusic(bed) {
  if (!SFX) return;
  const want = bed === 'intense' ? 'intense' : 'calm';
  if (!state.musicCalm) {
    // Start both beds together and leave them running. They share an exact
    // bar grid, so changing intensity is a gain crossfade, never a song reset.
    state.musicCalm = SFX.loop('music/bed-calm');
    state.musicIntense = SFX.loop('music/bed-intense');
    state.musicVolumes = { calm: 0, intense: 0 };
  }
  if (state.musicBed === want && state.musicVolumes[want] === 0.25) return;
  state.musicBed = want;
  if (state.musicFade) cancelAnimationFrame(state.musicFade);
  const from = { ...state.musicVolumes };
  const to = { calm: want === 'calm' ? 0.25 : 0, intense: want === 'intense' ? 0.25 : 0 };
  const started = performance.now();
  const fade = (now) => {
    const p = Math.min(1, (now - started) / 500);
    state.musicVolumes.calm = from.calm + (to.calm - from.calm) * p;
    state.musicVolumes.intense = from.intense + (to.intense - from.intense) * p;
    state.musicCalm.setVolume(state.musicVolumes.calm);
    state.musicIntense.setVolume(state.musicVolumes.intense);
    if (p < 1) state.musicFade = requestAnimationFrame(fade);
    else state.musicFade = 0;
  };
  state.musicFade = requestAnimationFrame(fade);
}

/** Roll volume and pitch follow the fastest ball, so the table sounds alive. */
function updateRollSound() {
  if (!SFX) return;
  const balls = state.world.balls.filter((b) => b.alive && !b.captured);
  const fastest = balls.reduce((m, b) => Math.max(m, Math.hypot(b.vx, b.vy)), 0);
  const onRamp = balls.some((b) => b.inRamp);

  if (!state.roll) {
    state.roll = SFX.loop('ball-roll');
    state.rampRoll = SFX.loop('ramp-roll');
    state.rampRoll.setVolume(0);
  }
  const n = Math.min(fastest / 2200, 1);
  state.roll.setVolume(onRamp ? 0 : 0.30 * n).setRate(0.7 + n * 0.8);
  state.rampRoll.setVolume(onRamp ? 0.30 : 0);
}

function stopContinuous() {
  if (state.roll) { state.roll.stop(); state.roll = null; }
  if (state.rampRoll) { state.rampRoll.stop(); state.rampRoll = null; }
  if (state.musicFade) { cancelAnimationFrame(state.musicFade); state.musicFade = 0; }
  if (state.musicCalm) { state.musicCalm.stop(); state.musicCalm = null; }
  if (state.musicIntense) { state.musicIntense.stop(); state.musicIntense = null; }
  state.musicBed = 'calm';
  state.musicVolumes = { calm: 0, intense: 0 };
}

function runPendingKicks(dt) {
  if (!state.pendingKicks.length) return;
  for (const k of state.pendingKicks) k.t -= dt;
  const due = state.pendingKicks.filter((k) => k.t <= 0);
  state.pendingKicks = state.pendingKicks.filter((k) => k.t > 0);
  for (const k of due) releaseSaucer(state.world, k.id);
}

function showLog(entries) {
  for (const entry of entries) announce(entry.text);
}

function onBallLost() {
  if (state.world.mode.endless) {
    serveBall(state.world);
    return;
  }

  // Ball save first: a saved ball is not a lost ball, so nothing advances --
  // not the ball number, not the bonus, not the count remaining.
  if (consumeBallSave(state.rules)) {
    serveBall(state.world);
    state.pendingKicks = [];
    announce('BALL SAVED');
    paint();
    return;
  }

  const bonus = nextBall(state.rules);

  // An extra ball is the same ball number over again, so it is spent here
  // rather than added to the count: the player sees "Ball 2 / 3" twice.
  if (consumeExtraBall(state.rules)) {
    state.rules.ball -= 1;
    armBallSave(state.rules);
    serveBall(state.world);
    state.pendingKicks = [];
    rollBonus(bonus, 'EXTRA BALL');
    return;
  }

  state.ballsLeft -= 1;
  if (state.ballsLeft <= 0) {
    // The final bonus is the one worth watching. Count it up, then end.
    state.running = false;
    rollBonus(bonus, 'Game over', () => gameOver(bonus));
    return;
  }
  serveBall(state.world);
  state.pendingKicks = [];
  rollBonus(bonus, `Ball ${state.rules.ball}`);
}

/*
 * The end-of-ball bonus was already tallied and paid; it was just handed over
 * instantly. The countdown IS the reward in pinball, so the SCORE DISPLAY is
 * animated up to the already-awarded total. Presentation only -- the rules
 * have the real number the whole time, so nothing here can desync the game.
 */
let rollTimer = 0;
function rollBonus(bonus, thenText, done) {
  clearInterval(rollTimer);
  const r = state.rules;
  if (!bonus || bonus <= 0) { state.rolling = false; announce(thenText); paint(); if (done) done(); return; }
  const steps = 12;
  const from = r.score - bonus;
  let i = 0;
  state.rolling = true;
  announce(`Bonus ${bonus.toLocaleString()}`);
  rollTimer = setInterval(() => {
    i += 1;
    const shown = Math.round(from + (bonus * i) / steps);
    el('pb-score').textContent = shown.toLocaleString();
    sfx('spinner-tick');
    if (i >= steps) {
      clearInterval(rollTimer);
      state.rolling = false;
      paint();
      announce(thenText);
      if (done) done();
    }
  }, 70);
}

function gameOver(bonus) {
  state.running = false;
  stopContinuous();
  clearInterval(rollTimer);
  state.rolling = false;
  sfx('game-over');
  const r = state.rules;
  if (bonus > 0) el('pb-score').textContent = r.score.toLocaleString();
  announce(`Game over. ${r.score.toLocaleString()} points.`);
  el('pb-overlay').hidden = false;
  el('pb-overlay-title').textContent = 'Game over';
  el('pb-overlay-body').textContent = `${r.score.toLocaleString()} points`;
  el('pb-overlay-note').textContent =
    `${RANKS[r.rank]} • ${r.missionsDone.length} of ${MISSIONS.length} missions`;
  showMatch(r.score);
  saveBest();
  if (state.resume) state.resume.clear();
  if (DAILY) markDailyDone();
  offerShare();
}

/**
 * Share on game over. The spoiler rule matters even here: the mission ORDER is
 * the daily's content, so the card reports how far you got, never which
 * missions came up.
 */
function offerShare() {
  if (!window.SnackPackShare) return;
  const r = state.rules;
  const filled = Math.min(r.missionsDone.length, MISSIONS.length);
  const row = '\u{1F7E9}'.repeat(filled) + '\u2B1C'.repeat(MISSIONS.length - filled);
  window.SnackPackShare.result({
    mount: document.querySelector('.pb-stage'),
    game: 'Pinball',
    puzzle: DAILY || undefined,
    headline: `${MODES[state.mode].label}: ${r.score.toLocaleString()} as ${RANKS[r.rank]}`,
    stats: [`${r.missionsDone.length}/${MISSIONS.length} missions`, `ball ${r.ball}`],
    grid: [row],
  });
}

const dailyKey = () => `pinball_daily_${DAILY}`;

function dailyAlreadyPlayed() {
  if (!DAILY) return false;
  try {
    if (window.SnackPackStore) return !!window.SnackPackStore.get('pinball', 'daily', DAILY);
    return !!localStorage.getItem(`sp_${dailyKey()}`);
  } catch (err) { return false; }
}

function markDailyDone() {
  try {
    const v = String(state.rules.score);
    if (window.SnackPackStore) window.SnackPackStore.set('pinball', 'daily', DAILY, v);
    else localStorage.setItem(`sp_${dailyKey()}`, v);
  } catch (err) { /* storage can be blocked; never break the game over it */ }
}

// ---------------------------------------------------------------------------
// Persistence -- arcade convention, sp_-prefixed via SnackPackStore
// ---------------------------------------------------------------------------

const bestKey = () => `pinball_best_${state.mode}`;

function readBest() {
  try {
    if (window.SnackPackStore) return Number(window.SnackPackStore.get('pinball', 'best', state.mode)) || 0;
    return Number(localStorage.getItem(`sp_${bestKey()}`)) || 0;
  } catch (err) { return 0; }
}

function saveBest() {
  try {
    if (state.rules.score <= readBest()) return;
    if (window.SnackPackStore) window.SnackPackStore.set('pinball', 'best', state.mode, state.rules.score);
    else localStorage.setItem(`sp_${bestKey()}`, String(state.rules.score));
  } catch (err) { /* storage can be blocked; never break the game over it */ }
}

// ---------------------------------------------------------------------------
// UI
// ---------------------------------------------------------------------------

function paint() {
  const r = state.rules;
  // While the bonus is counting up, the roll owns the score display. paint()
  // runs every frame, so without this it overwrote each step within ~16ms and
  // the countdown was invisible.
  if (!state.rolling) el('pb-score').textContent = r ? r.score.toLocaleString() : '0';
  // nextBall() increments before the game-over check, so the last drain would
  // otherwise read "Ball 4 / 3" while the final bonus counts up.
  const ballCount = MODES[state.mode].balls;
  el('pb-ball').textContent = state.world && state.world.mode.endless
    ? '∞'
    : `${Math.min(r ? r.ball : 1, ballCount)} / ${ballCount}`;
  el('pb-best').textContent = readBest().toLocaleString();
  el('pb-rank').textContent = r ? RANKS[r.rank] : RANKS[0];
  if (r) el('pb-dmd').textContent = statusLine(r);
  paintCombo(r);
  paintTilt(state.world);
}

/**
 * A combo multiplies everything you shoot and expires on a timer, and until now
 * nothing on screen said so. The bar is the time left to keep it alive, which is
 * the only part the player can act on.
 */
function paintCombo(r) {
  const chip = el('pb-combo-chip');
  if (!r || r.combo < 2) { chip.hidden = true; return; }
  chip.hidden = false;
  el('pb-combo').textContent = `${Math.min(r.combo, 5)}x`;
  const left = Math.max(0, Math.min(1, r.comboTimer / COMBO_WINDOW));
  el('pb-combo-fill').style.width = `${Math.round(left * 100)}%`;
}

/**
 * Tilt is the one mechanic that can take a ball away without the player
 * understanding why. The meter stays hidden until the first nudge, so it costs
 * nothing until the moment it becomes the answer to "what just happened".
 */
function paintTilt(w) {
  const chip = el('pb-tilt-chip');
  if (!w || (w.tilt <= 0 && !w.tilted)) { chip.hidden = true; return; }
  const limit = w.mode.tiltWarnings || 1;
  const filled = Math.max(0, Math.min(1, w.tilt / limit));
  chip.hidden = false;
  chip.dataset.state = w.tilted ? 'tilted' : filled >= 0.66 ? 'warn' : 'ok';
  el('pb-tilt-fill').style.width = `${Math.round((w.tilted ? 1 : filled) * 100)}%`;
}

let announceTimer = 0;
function announce(text) {
  const live = el('pb-live');
  live.textContent = text;
  const banner = el('pb-banner');
  banner.textContent = text;
  banner.hidden = false;
  clearTimeout(announceTimer);
  announceTimer = setTimeout(() => { banner.hidden = true; }, 1600);
}

function describeTable() {
  if (!state.world || !state.rules) return 'Pinball table';
  const b = state.world.balls.find((x) => x.alive);
  if (!b || !state.rules) return 'Pinball table, ball lost';
  const where = b.y < 300 ? 'the top arch' : b.y < 700 ? 'the middle of the table' : 'near the flippers';
  const r = state.rules;
  return `Pinball. Score ${r.score}. Ball ${r.ball}. ${statusLine(r)}. Ball is at ${where}.`;
}

// ---------------------------------------------------------------------------
// Start / mode select
// ---------------------------------------------------------------------------

function start(modeId) {
  if (DAILY && dailyAlreadyPlayed()) {
    announce("Today's challenge is already played. Come back tomorrow.");
    return;
  }
  state.mode = modeId;
  const seed = seedForRun();
  state.seed = seed;
  state.world = createWorld(modeId, seed);
  state.rules = createRules(seed, modeId);
  // createRules starts the game on ball 1 without going through nextBall, so
  // the first ball would otherwise be the only one with no save.
  armBallSave(state.rules);
  state.tape = RECORD ? [] : null;
  state.ballsLeft = MODES[modeId].balls;
  state.pendingKicks = [];
  state.running = true;
  state.paused = false;
  state.flashes.clear();
  el('pb-overlay').hidden = true;
  el('pb-modes').hidden = true;
  el('pb-hud').hidden = false;
  state.renderer.resize();
  setMusic('calm');
  paint();
  announce(`${MODES[modeId].label}. Hold the plunger.`);
}

/** Daily runs share a seed, so everyone gets the same missions in the same order. */
function seedForRun() {
  if (DAILY) {
    let h = 2166136261;
    for (let i = 0; i < DAILY.length; i += 1) {
      h ^= DAILY.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return h >>> 0;
  }
  return (Date.now() ^ Math.floor(Math.random() * 0xffffffff)) >>> 0;
}

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

const KEYS_LEFT = ['KeyZ', 'ArrowLeft', 'ShiftLeft'];
const KEYS_RIGHT = ['Slash', 'ArrowRight', 'ShiftRight'];
// Space is the convention, but Up is what people reach for when the plunger is
// drawn at the bottom of a portrait table, and it is otherwise unbound.
const KEYS_PLUNGE = ['Space', 'ArrowUp'];

/**
 * Flipper sound follows the BUTTON, not the ball. A flipper makes its noise
 * whether or not it hits anything, and up and down are different samples --
 * one shared flipper sound is the commonest tell of an amateur pinball game.
 */
function flipperSound(down) {
  sfx(down ? 'flipper-up' : 'flipper-down');
}

/**
 * The plunger's RELEASE is an engine event (EVENT_SFX.plunge), because the ball
 * leaving the lane is a physics fact. The pull is not -- it is pure input, and
 * it is the part the player is actually doing, so it needs its own cue here or
 * charging the plunger is silent. plunger-pull.wav existed with no caller.
 */
function plungerSound(down) {
  if (down) sfx('plunger-pull');
}

/*
 * MATCH. A real cabinet rolls two digits at game over and gives a free credit
 * when they match the score's last two. Here the game is already free, so the
 * credit has nothing to buy -- the reveal is the whole point, and pretending it
 * grants something would be inventing stakes that do not exist. One in ten,
 * exactly as on a real table.
 */
function showMatch(score) {
  const el2 = el('pb-match');
  if (!el2) return;
  const drawn = Math.floor(Math.random() * 10) * 10;
  const mine = score % 100;
  const hit = drawn === mine - (mine % 10);
  el2.hidden = false;
  el2.textContent = `MATCH ${String(drawn).padStart(2, '0')}`;
  el2.dataset.hit = hit ? 'yes' : 'no';
  if (hit) {
    el2.textContent = `MATCH ${String(drawn).padStart(2, '0')} — free game`;
    sfx('rank-up');
  }
}

function bindKeys() {
  window.addEventListener('keydown', (e) => {
    if (e.repeat) return;
    if (KEYS_LEFT.includes(e.code)) { state.input.left = true; flipperSound(true); e.preventDefault(); }
    else if (KEYS_RIGHT.includes(e.code)) { state.input.right = true; flipperSound(true); e.preventDefault(); }
    else if (KEYS_PLUNGE.includes(e.code)) { state.input.plunge = true; plungerSound(true); e.preventDefault(); }
    else if (e.code === 'Comma' && state.world) nudge(state.world, -1, 0);
    else if (e.code === 'Period' && state.world) nudge(state.world, 1, 0);
    else if (e.code === 'KeyN' && state.world) nudge(state.world, 0, -1);
  });
  window.addEventListener('keyup', (e) => {
    if (KEYS_LEFT.includes(e.code)) { state.input.left = false; flipperSound(false); }
    else if (KEYS_RIGHT.includes(e.code)) { state.input.right = false; flipperSound(false); }
    else if (KEYS_PLUNGE.includes(e.code)) state.input.plunge = false;
  });
}

/**
 * Touch: full-height columns, not buttons near the flippers -- a player's
 * thumbs rest at the bottom of a phone, and both flippers at once is not
 * optional in pinball, so each pointer is tracked by id.
 *
 * Coordinates come from getBoundingClientRect, never pageX. Brain Games has a
 * live defect from exactly that: pageX breaks under a transformed game area.
 */
function bindTouch(stage) {
  const zones = new Map();

  const zoneFor = (clientX) => {
    const r = stage.getBoundingClientRect();
    const f = (clientX - r.left) / r.width;
    if (f < 0.34) return 'left';
    if (f > 0.66) return 'right';
    return 'plunge';
  };

  const apply = () => {
    const active = new Set(zones.values());
    const wasLeft = state.input.left;
    const wasRight = state.input.right;
    const wasPlunge = state.input.plunge;
    state.input.left = active.has('left');
    state.input.right = active.has('right');
    state.input.plunge = active.has('plunge');
    if (state.input.left !== wasLeft) flipperSound(state.input.left);
    if (state.input.right !== wasRight) flipperSound(state.input.right);
    if (state.input.plunge && !wasPlunge) plungerSound(true);
  };

  stage.addEventListener('pointerdown', (e) => {
    // Anything interactive inside the stage -- the mode buttons, the game-over
    // button -- must keep working. Capturing the pointer and calling
    // preventDefault here swallows the click before it ever reaches them, so a
    // player simply could not start a game by tapping. Bail out early instead.
    if (e.target.closest('button, a, [role="button"]')) return;
    if (!state.running) return;

    stage.setPointerCapture(e.pointerId);
    zones.set(e.pointerId, zoneFor(e.clientX));
    apply();
    e.preventDefault();
  });
  const release = (e) => { zones.delete(e.pointerId); apply(); };
  stage.addEventListener('pointerup', release);
  stage.addEventListener('pointercancel', release);
  stage.addEventListener('pointerleave', release);
}

// ---------------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------------

function boot() {
  const canvas = el('pb-canvas');
  const stage = canvas.parentElement;
  state.renderer = createRenderer(canvas);
  state.world = createWorld('classic', 1);

  bindKeys();
  bindTouch(stage);
  window.addEventListener('resize', () => state.renderer.resize());

  for (const btn of document.querySelectorAll('[data-mode]')) {
    btn.addEventListener('click', () => start(btn.dataset.mode));
  }
  el('pb-again').addEventListener('click', () => {
    el('pb-overlay').hidden = true;
    el('pb-modes').hidden = false;
    el('pb-hud').hidden = true;
    state.running = false;
  });

  // Shared arcade pause. It stops the accumulator; rAF keeps running so the
  // table stays painted.
  if (window.SnackPackPause) {
    window.SnackPackPause.attach({
      mount: document.querySelector('.pb-controls'),
      stage,
      isPlaying: () => state.running && !state.paused,
      pause: () => { state.paused = true; },
      resume: () => { state.paused = false; state.last = 0; },
    });
  }

  // Saved progress. The world itself is NOT serialised: restoring a ball
  // mid-flight would drop the player into a physics state they did not
  // create, mid-air and mid-shot. Resuming instead returns the ball to the
  // plunger with the score, rank, missions and ball number intact -- which is
  // what a real machine does when the power comes back.
  if (window.SnackPackResume) {
    state.resume = window.SnackPackResume.attach({
      game: 'pinball',
      variant: () => state.mode,
      schemaVersion: 1,
      serialize: () => ({
        mode: state.mode,
        ballsLeft: state.ballsLeft,
        rules: serializeRules(state.rules),
      }),
      validate: (p) => !!p && typeof p.mode === 'string' && !!p.rules
        && typeof p.rules.score === 'number',
      restore: (p) => {
        state.mode = p.mode;
        state.rules = deserializeRules(p.rules);
        state.world = createWorld(p.mode, state.rules.seed);
        state.ballsLeft = p.ballsLeft;
        state.pendingKicks = [];
        state.running = true;
        state.paused = false;
        el('pb-modes').hidden = true;
        el('pb-overlay').hidden = true;
        el('pb-hud').hidden = false;
        state.renderer.resize();
        state.lit = litShots(state.rules);
        paint();
        announce('Resumed');
        return true;
      },
      isActive: () => state.running && state.rules && state.rules.score > 0,
    });
  }

  // Keep the accessible description current without touching it every frame.
  setInterval(() => { canvas.setAttribute('aria-label', describeTable()); }, 1200);

  paint();
  state.raf = requestAnimationFrame(frame);
}

if (RECORD) {
  window.__pbTape = () => ({
    kind: 'frames',
    name: `human-${state.mode}-${state.seed}`,
    seed: state.seed,
    mode: state.mode,
    frames: state.tape || [],
  });
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
else boot();
